version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: madoka_postgres
    environment:
      POSTGRES_DB: madokadb
      POSTGRES_USER: madoka
      POSTGRES_PASSWORD: madoka_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      - madoka_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U madoka -d madokadb"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    container_name: madoka_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    networks:
      - madoka_net
    depends_on:
      - postgres

networks:
  madoka_net:
    driver: bridge