version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: madoka_postgres
    environment:
      POSTGRES_DB: madokadb
      POSTGRES_USER: madoka
      POSTGRES_PASSWORD: madoka_postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      - madoka_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U madoka -d madokadb"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  madoka_net:
    driver: bridge